% Motor Modell F1404 KV4600 + GF3016
% Basierend auf Messdaten (50-100% Gas)
clear; clc;

% =========================================================
% 1. Standtest-Daten (für Gas 50-100%%, GF3016)
% =========================================================
% throttle, Gasstellung [%]
gas_pct =     [0, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]';
% RPM, Drehzahl [U/min]
drehzahl_upm = [0, 26532, 28299, 30006, 31559, 32770, 34340, 35813, 37190, 38436, 39376, 40053]';
% Thrust, Schubkraft [g]
schub_g =     [0, 184.21, 210.22, 233.36, 254.72, 268.50, 287.60, 300.59, 316.02, 330.89, 340.24, 344.73]';
% Spannung [V], Stromaufnahme [A], Leistungaufnahme [W]
spannung_v =  [13.95, 15.93, 15.91, 15.88, 15.85, 15.84, 15.81, 15.78, 15.75, 15.71, 15.68, 15.64]';
strom_a =     [0.60, 5.23, 6.37, 7.64, 8.85, 10.01, 11.32, 12.50, 13.70, 14.98, 16.24, 17.54]';
leistung_w =  [0, 83.28, 101.26, 121.40, 140.28, 158.49, 178.95, 197.32, 215.83, 235.41, 254.54, 274.32]';

lut_size = 101; % Zahl der LUT-Datei für motor.cpp
MOTOR_I_IDLE = 0.60;
% Hover-Gassstellung für 250g-Quad bei 15.8V berechnen
% 62.5g pro Motor nötig → RPM lösen → LUT interpolieren
hover_voltage   = 15.8;
hover_v_nominal = 16.0;
drone_mass_g    = 250.0;
n_motors        = 4;

% 1. Zuerst normalisieren wir die Drehzahl auf das nominale Spannung (16V), damit die Polynomfits später für 16V gültig sind
% RPM skaliert mit (V_nominal / V_aktuell), da RPM ~ V für BLDC-Motoren (unter Last) physikalisch zu erwarten ist
drehzahl_norm = drehzahl_upm .* (hover_v_nominal ./ spannung_v);

% =========================================================
% 2. Regressionsanalyse (Curve Fitting)
% =========================================================
% A) Schubmodell: F(n) = A*n^2 + B*n + C
p_schub = polyfit(drehzahl_upm, schub_g, 2); % F(n) rein aerodynamisch — Messwerte bei echtem RPM verwenden

% B) Strommodell: I(gas) = Ai*g^2 + Bi*g + Ci (gas 0.0 - 1.0)
strom_a_norm = strom_a .* (hover_v_nominal ./ spannung_v ).^2;
strom_a_norm(1) = MOTOR_I_IDLE;  % idle current: friction-dominated, not V²-dependent
p_strom = polyfit(gas_pct/100, strom_a_norm, 2);

% C) Physikalische Schubmodell: F = k*n^2 (durch Ursprung, ohne freiheitsgrad)
% Punkt (0,0) wird NICHT gefittet - er ist Randbedingung, kein Messwert
drehzahl_fit = drehzahl_upm(2:end);
schub_fit = schub_g(2:end);
k_fit = sum(schub_fit .* drehzahl_fit.^2) / sum(drehzahl_fit.^4);

% =========================================================
% 3. Generierung der motor_lut.h
% =========================================================

gas_lut = linspace(0, 1, lut_size); % Gleichmäßiges Gitter 0.0, 0.01, 0.02 ... 1.0

% RPM polynomisch approximieren
p_rpm_fit = polyfit(gas_pct/100, drehzahl_norm, 2);
rpm_lut = max(0, polyval(p_rpm_fit, gas_lut));
rpm_lut(1) = 0.0; % Nullpunkt erzwingen, auch wenn Polynom leicht negativ ist

% Strom polynomisch approximieren
curr_lut = max(MOTOR_I_IDLE, polyval(p_strom, gas_lut));

% Schub [g] bei nominaler Spannung (MOTOR_V_NOMINAL = 16V)
% Berechnet über rpm_lut — Polynom bereits angewendet, zur Laufzeit nicht mehr benötigt
schub_lut = max(0, polyval(p_schub, rpm_lut));

k_volt          = hover_voltage / hover_v_nominal;
thrust_per_motor = drone_mass_g / n_motors;  % 62.5g

Ap = p_schub(1) * k_volt^2;
Bp = p_schub(2) * k_volt;
Cp = p_schub(3) - thrust_per_motor;
rpm_nom_hover = (-Bp + sqrt(Bp^2 - 4*Ap*Cp)) / (2*Ap);

hover_throttle = interp1(rpm_lut, gas_lut, rpm_nom_hover, 'linear', 'extrap');
hover_throttle = max(0.0, min(1.0, hover_throttle));

fid = fopen('../includes/motor_lut.h', 'w');
if fid == -1
    error('Datei konnte nicht geöffnet werden: ../includes/motor_lut.h');
end

fprintf(fid, '// AUTO-GENERATED by motor_model.m (101 points smooth LUT)\n');
fprintf(fid, '#ifndef MOTOR_LUT_H\n#define MOTOR_LUT_H\n\n');

fprintf(fid, 'static constexpr float MOTOR_V_NOMINAL = 16.0f;\n');
fprintf(fid, 'static constexpr float MOTOR_I_IDLE    = 0.60f;\n\n');
fprintf(fid, '// Hover throttle for a 250g quad (4x F1404) at ~15.8V (slightly discharged 4S)\n');
fprintf(fid, '// 62.5g per motor required; calculated from thrust polynomial + RPM LUT\n');
fprintf(fid, 'static constexpr float MOTOR_HOVER_THROTTLE_250G = %.4ff;\n\n', hover_throttle);

fprintf(fid, 'static constexpr int MOTOR_TAB_SIZE = %d;\n\n', lut_size);

fprintf(fid, 'static constexpr float MOTOR_TAB_GAS[] = {');
fprintf(fid, '%.2ff, ', gas_lut);
fprintf(fid, '};\n\n');

fprintf(fid, 'static constexpr float MOTOR_TAB_DREHZAHL[] = {');
fprintf(fid, '%.1ff, ', rpm_lut);
fprintf(fid, '};\n\n');

fprintf(fid, 'static constexpr float MOTOR_TAB_STROM[] = {');
fprintf(fid, '%.3ff, ', curr_lut);
fprintf(fid, '};\n\n');

% Schub bei 16V, berechnet über Polynom F(n) mit n aus rpm_lut
schub_lut_N = schub_lut / 1000.0 * 9.81; % Umrechnung von g in Newton
fprintf(fid, 'static constexpr float GRAMS_TO_NEWTONS = %.6ff;\n\n', 9.81/1000.0);
fprintf(fid, 'static constexpr float MOTOR_TAB_SCHUB_N[] = {');
fprintf(fid, '%.6ff, ', schub_lut_N);
fprintf(fid, '};\n\n');

fprintf(fid, '#endif\n');
fclose(fid);

% =========================================================
% 4. Visualisierung (Zwei-Fenster-Grafik)
% =========================================================
% --- 4. Visualisierung und Speichern ---
% 1. Erstellen des Plots-Verzeichnisses, falls nicht vorhanden
plot_dir = '../plots';
if ~exist(plot_dir, 'dir')
    mkdir(plot_dir);
end

% 2. Temporäre Achsen
n_plot = linspace(0, max(drehzahl_upm), 1000);
g_plot = linspace(0, 1.1, 200);

% 3. Fehlerbehebung: Verwenden des punktweisen Maximums
% polyval gibt einen Vektor zurück, daher vergleichen wir ihn mit 0 über max(Skalar, Vektor)
f_raw = polyval(p_schub, n_plot);
f_plot = max(0, f_raw);

i_raw = polyval(p_strom, g_plot);
motor_i_idle = 0.60; % Idle-Strom, nicht unterschreiten
i_plot = max(motor_i_idle, i_raw);


% --- Vorbereitung der Daten für RPM---
% 1. Nehmen wir den Referenzpunkt (100% Gas am Standtest)
n_real_max = 40053;

% CT aus der Physik (nicht k aus einem Punkt)
rho = 1.225;
D_prop = 0.0762;  %GF3016 = 3'' = 76.2mm
r_prop = D_prop / 2;
A_prop = pi * r_prop^2;
omega_ds = drehzahl_upm(2:end) * pi / 30;
F_ds_N = schub_g(2:end) / 1000 * 9.81;
CT = mean(F_ds_N ./ (rho * A_prop * r_prop^2 * omega_ds.^2));

n_limit_ideal = 73600; % KV * V = 4600 * 16.0
gas_sim = linspace(0, 1, 200);

% A) Ideal: RPM linear from Gas, Thrust via CT
n_ideal_x = linspace(0, n_limit_ideal, 200); % schneidet Linie bei 73.6k RPM
omega_ideal = n_ideal_x * pi / 30;
f_ideal_y = CT * rho * A_prop * r_prop^2 * omega_ideal.^2 / 9.81 * 1000;

% B) Real Stand: RPM from polynomial, Thrust via CT
gas_sim_ext = linspace(0, 1.2, 200);
n_analyt_x = max(0, polyval(p_rpm_fit, gas_sim_ext));
n_analyt_x = min(n_analyt_x, 48000);

omega_analyt = n_analyt_x * pi / 30;
f_analyt_y = CT * rho * A_prop * r_prop^2 * omega_analyt.^2 / 9.81 * 1000;


% --- Plot 1: Schub-Drehzahl-Kennlinie F(n) ---
fig1 = figure('Name', 'Schub_Drehzahl', 'Color', 'w');

% Grün Ideal (Theoretisches Limit)
plot(n_ideal_x, f_ideal_y, 'g--', 'LineWidth', 1.5, 'DisplayName', 'Theoretisches Limit (73.7k)');
hold on;
% Senkrechte Linie von max Ideal zur X-Achse
n_max_ideal = n_ideal_x(end);   % 73600 RPM
f_max_ideal = f_ideal_y(end);   % 344.73 g
plot([n_max_ideal n_max_ideal], [0, f_max_ideal], 'k--', 'LineWidth', 1.0, ...
    'HandleVisibility', 'off');   % nicht in Legende

% Magenta Real (Analytisches Modell aus Standtest)
plot(n_analyt_x, f_analyt_y, 'm-', 'LineWidth', 1.5, 'DisplayName', 'Analytisches Modell (48k)');
% Senkrechte Linie von max Analytisch zur X-Achse
n_max_analyt = n_analyt_x(end);   % 48000 RPM
f_max_analyt = f_analyt_y(end);  % 344.73 g
plot([n_max_analyt n_max_analyt], [0, f_max_analyt], 'k--', 'LineWidth', 1.0, ...
    'HandleVisibility', 'off');   % nicht in Legende

    % Blau Messdaten
plot(drehzahl_upm, schub_g, 'ro', 'MarkerFaceColor', 'r', 'DisplayName', 'Messdaten(Standtest)');
f_phys = k_fit * n_plot.^2;
plot(n_plot, f_phys, 'b-', 'LineWidth', 1.5, 'DisplayName', 'Physikalisches Modell F=k*n^2');
% Senkrechte Linie von max Messpunkt zur X-Achse
n_max_mess = drehzahl_norm(end);   % 40053 RPM
f_max_mess = schub_g(end);        % 344.73 g
plot([n_max_mess n_max_mess], [0, f_max_mess], 'k--', 'LineWidth', 1.0, ...
    'HandleVisibility', 'off');   % nicht in Legende



title('F1404 KV4600 + GF3016 — Schub-Drehzahl-Kennlinie');
xlabel('Drehzahl n [U/min]');
ylabel('Schubkraft F [g]');
xlim([0, n_limit_ideal * 1.05]);
%ylim([0, 1200]);
ylim([0, max(f_ideal_y)*1.1]);
grid on;
legend('Location', 'northwest');
saveas(fig1, fullfile(plot_dir, 'plot1_schub_drehzahl.png'));


% --- Plot 2: Stromaufnahme vs Schubkraft ---
fig2 = figure('Name', 'Strom_Schub', 'Color', 'w');
% Fit: Leerlaufstrom ignorieren — Idle-Strom ist ein Sonderfall
F_mess = schub_g(2:end);
I_mess = strom_a_norm(2:end);

p_I_F = polyfit(F_mess, I_mess, 3);
%F_plot = linspace(0, max(F_mess) * 1.02, 200);
F_plot = linspace(min(F_mess), max(F_mess) * 1.02, 200);  % Start ab erster Messpunkt
I_fit  = polyval(p_I_F, F_plot);
%I_fit  = max(I_fit, MOTOR_I_IDLE);  % nicht unter Leerlaufstrom

plot(F_mess, I_mess, 'rs', 'MarkerFaceColor', 'r', 'DisplayName', 'Messdaten @ 16V (normalisiert)');  % b → r
hold on;
plot(F_plot, I_fit, 'b-', 'LineWidth', 1.5, 'DisplayName', 'Fit I(F) kubisch');                     % r → b

title('F1404 KV4600 + GF3016 — Strom-Schub-Kennlinie I(F) @ 16V');
xlabel('Schubkraft F [g]');
ylabel('Stromaufnahme I [A]');
grid on;
legend('Location', 'northwest');
saveas(fig2, fullfile(plot_dir, 'plot2_strom_schub.png'));


% --- Plot 3: Propeller-Effizienz eta = F/P [g/W] ---
fig3 = figure('Name', 'Leistung_Schub', 'Color', 'w');
F_mess  = schub_g(2:end);
P_mess  = leistung_w(2:end);
eta_mess = F_mess ./ P_mess;  % g/W

% Polynom fit
p_eta = polyfit(F_mess, eta_mess, 1);

F_eta_plot = linspace(min(F_mess), max(F_mess) * 1.02, 200);  % Start ab erster Messpunkt
eta_fit    = polyval(p_eta, F_eta_plot);

plot(F_mess, eta_mess, 'rs', 'MarkerFaceColor', 'r', 'DisplayName', 'Messdaten η [g/W]');
hold on;
plot(F_eta_plot, eta_fit, 'b-', 'LineWidth', 2, 'DisplayName', 'Fit η(F)');


% Hover-Punkt markieren
hover_F = 62.5;  % g pro Motor für 250g Quad

% Extrapoliere eta zum hover punkt
eta_hover = polyval(p_eta, hover_F);
x_grenze = min(F_mess);
y_max    = max(eta_mess);
y_min    = min(eta_mess);

%plot(hover_F, eta_hover, 'm^', 'MarkerFaceColor', 'm', 'MarkerSize', 10, ...
%'DisplayName', sprintf('Hover 62.5g -> %.2f g/W', eta_hover));

% Hover-Marker nur als vertikale Linie — nicht als Punkt (liegt ausserhalb Messdaten)
plot([x_grenze x_grenze], [y_min * 0.9, y_max * 1.1], 'k--', 'LineWidth', 1.5, ...
    'DisplayName', 'Messbereich-Grenze (50% Gas)');
text(x_grenze + 2, y_min + (y_max - y_min) * 0.7, ...
    sprintf('\\leftarrow Hover liegt hier\n   (Extrapolation)\n   \\eta \\approx %.2f g/W', eta_hover), ...
    'FontSize', 8, 'Color', 'black');

title('F1404 KV4600 + GF3016 — Propeller-Effizienz η = F/P [g/W]');
xlabel('Schubkraft F [g]');
ylabel('η [g/W]');
ylim([y_min * 0.9, y_max * 1.15]);
grid on;
legend('Location', 'northeast');
saveas(fig3, fullfile(plot_dir, 'plot3_leistung_schub.png'));

% Alle Figuren offen lassen (zum Prüfen)
%close(fig1); close(fig2); close(fig3);